name: update_dependencies

on:
  workflow_dispatch:
    inputs:
      draft:
        description: 'Create a draft pull request.'
        required: false
        default: "false"
  schedule:
    # build every night at 0:00
    - cron:  '0 0 * * *'

jobs:
  update-dependencies:
    runs-on: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Checkout latest master on submodules
      shell: bash
      run: |
        git submodule status
        git submodule foreach "git fetch; git checkout master; git pull; git status"
        git submodule status
    - name: Git Status
      shell: bash
      id: extract_information
      run: |
        status=$(git submodule status)
        status="${status//'%'/'%25'}"
        status="${status//$'\n'/'%0A'}"
        status="${status//$'\r'/'%0D'}"
        echo "::set-output name=status::$status"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ steps.generate-token.outputs.token }}
        title: '[Bot] Update Submodules to Latest Master'
        body: |
          Some submodules can be updated:

          ${{ steps.extract_information.outputs.status }}

          Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        commit-message: "ðŸ¤– Update submodules to latest master"
        assignees: betwo
        reviewers: betwo
        branch: feature/update-submodules
        draft: ${{ github.event.inputs.draft }}
